# This file is used to run the Eidolon server, a MongoDB database, and the Eidolon UI together in a single command.
# Run `docker-compose up` in the same directory as this file to start the services.
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  eidolon-server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - EIDOLON_VERSION=latest
    platform: linux/amd64
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AGENT_DIRECTORY=/app/resources
      - MONGO_CONNECTION_STR=mongodb://mongo:27017
      - DISABLE_ANONYMOUS_METRICS=true
    expose:
      - "8080"
    ports:
      - "8080:8080"
    volumes:
      - ./examples/eidolon_examples/conversational_chatbot/resources:/app/resources
    depends_on:
      - mongo

  eidolon-ui2:
    build:
      context: ./webui
      dockerfile: Dockerfile
    environment:
      - NEXTAUTH_URL=http://localhost:3000/api/auth
      - AUTH_TRUST_HOST=http://localhost:3000
      - NEXTAUTH_SECRET=secret
      - EIDOLON_SERVER=http://eidolon-server:8080
      - NEXT_PUBLIC_API_URL=http://localhost:3000
      - NEXT_PUBLIC_DEBUG=true
      - NEXT_PUBLIC_LOG_LEVEL=DEBUG
    ports:
      - "3000:3000"
    depends_on:
      - eidolon-server

volumes:
  mongo-data: