name: Rev and Publish Python Projects
on:
  workflow_run:
    workflows: ["Test"]  # The name of the test workflow
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rev:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: "Versioning Eidolon Dependencies"
        run: |
          make version
          echo "TAGGING_MESSAGE=$(make -C scripts -s run get_tags)" >> $GITHUB_ENV
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "bumping versions"
          tagging_message: ${{ env.TAGGING_MESSAGE }}

  publish_pypi:
    runs-on: ubuntu-latest
    needs: rev
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: "Publishing changes to PyPI"
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          make publish

  docker_sdk:
    runs-on: ubuntu-latest
    needs: rev
    steps:
      - uses: actions/checkout@v4
      - name: "Versioning Eidolon Dependencies"
        run: make maybe_docker_push
        working-directory: sdk

  docker_examples:
    runs-on: ubuntu-latest
    needs: [rev, docker_sdk]
    steps:
      - uses: actions/checkout@v4
      - name: "Versioning Eidolon Dependencies"
        run: make maybe_docker_push
        working-directory: examples

  docker_webui:
    runs-on: ubuntu-latest
    needs: rev
    steps:
      - uses: actions/checkout@v4
      - name: "Versioning Eidolon Dependencies"
        run: npm run maybe_docker_push
        working-directory: webui
